

Orlando Rodrigues de Lira

Paulo Isidorio Veloso

Priscila de Cássia Tavares Silva

Washington Henrique Nepomuceno

Dataset Fonte:
https://www.kaggle.com/datasets/nailasrivastava/life-expectancy-analysis?resource=download

In [200]:
import numpy as np
import pandas as pd
df = pd.read_csv("Life Expectancy Data.csv")
df.head(5)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [202]:
df.info()

#O conjunto de dados apresenta variáveis do tipo numéricas (inteiras e decimais)
# categóricas (texto).

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [203]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [187]:
df.isnull().sum()

#Observa-se que variáveis relacionadas a dados socioeconômicos e de saúde
#apresentam maior quantidade de valores faltantes, o que pode indicar dificuldade
#na coleta desses dados em alguns países.

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [123]:
df.nunique()
#Variáveis categóricas apresentam poucos valores distintos,
#enquanto variáveis numéricas contínuas possuem grande quantidade de valores únicos,
#refletindo a heterogeneidade dos países ao longo dos anos analisados.
#A análise dos valores distintos mostrou que o conjunto de dados contém informações
#de 193 países ao longo de 16 anos.

Country                             193
Year                                 16
Status                                2
Life expectancy                     362
Adult Mortality                     425
infant deaths                       209
Alcohol                            1076
percentage expenditure             2328
Hepatitis B                          87
Measles                             958
 BMI                                608
under-five deaths                   252
Polio                                73
Total expenditure                   818
Diphtheria                           81
 HIV/AIDS                           200
GDP                                2490
Population                         2278
 thinness  1-19 years               200
 thinness 5-9 years                 207
Income composition of resources     625
Schooling                           173
dtype: int64

In [124]:
df.describe()
#A análise descritiva evidenciou alta dispersão nos dados, especialmente em variáveis
#como mortalidade, PIB e população, indicando forte heterogeneidade entre os países.
#Além disso, foram identificados valores extremos que podem influenciar as análises
#estatísticas.

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [204]:
#Retirando espaços e padronizando o nome das colunas.
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [205]:
#Trocando vírgula por ponto
df = df.replace(',', '.', regex=True)

Questões:

In [212]:
#1.Qual é a expectativa de vida média global?
print(df.life_expectancy.mean())

69.22493169398908

In [191]:
#2. Em quais países desenvolvidos vivem mais?
df.groupby('status', as_index=False)['life_expectancy'].mean()
#Países desenvolvidos vivem, em média, 12 anos a mais
#diferença muito significativa.

       status  life_expectancy
0   Developed        79.197852
1  Developing        67.111465

In [207]:
#3.Faça uma comparação envolvendo mínimo, média e máximo.
df.groupby('status')['life_expectancy'].agg(['mean', 'min', 'max'])
#A análise por grupo mostrou que países desenvolvidos apresentam maior expectativa
#de vida média (79,19 anos) em comparação aos países em desenvolvimento (67,11 anos).
#Além disso, os países em desenvolvimento apresentam valores mínimos significativamente
#menores (36,3 anos), evidenciando condições mais críticas em alguns casos.
#Apesar disso, ambos os grupos podem atingir valores máximos semelhantes (89 anos),
#indicando que países em desenvolvimento também podem alcançar altos níveis de longevidade.
#Os resultados evidenciam desigualdade global na qualidade de vida e acesso à saúde.

                 mean   min   max
status
Developed   79.197852  69.9  89.0
Developing  67.111465  36.3  89.0

In [193]:
#4.Calcular a média da expectativa de vida no Brasil.
df[df['country'] == 'Brazil'].groupby('status')['life_expectancy'].mean()
#Ao analisar especificamente o Brasil, observa-se uma expectativa de vida média
#de 73,38 anos, valor superior à média dos países em desenvolvimento,
#indicando uma posição intermediária no cenário global.

status
Developing    73.38125
Name: life_expectancy, dtype: float64

In [196]:
#5.Quais países têm maior expectativa de vida?
df.groupby('country')['life_expectancy'] \
  .mean() \
  .sort_values(ascending=False) \
  .head(10)

country
Japan          82.53750
Sweden         82.51875
Iceland        82.44375
Switzerland    82.33125
France         82.21875
Italy          82.18750
Spain          82.06875
Australia      81.81250
Norway         81.79375
Canada         81.68750
Name: life_expectancy, dtype: float64

In [213]:
df_brasil = df[df['country'] == 'Brazil']

In [197]:
#6.O que mais influencia a expectativa de vida no Brasil?
#Os fatores mais associados ao aumento da expectativa de vida incluem melhorias
#ao longo do tempo, desenvolvimento econômico e maior investimento em saúde.
#Por outro lado, indicadores como desnutrição e mortalidade infantil apresentam
#forte correlação negativa, e videnciando seu impacto direto na redução da longevidade.
df_brasil.corr(numeric_only=True)['life_expectancy'].sort_values(ascending=False)

life_expectancy                    1.000000
year                               0.707907
alcohol                            0.704266
income_composition_of_resources    0.657779
total_expenditure                  0.606956
gdp                                0.529894
measles                            0.455630
percentage_expenditure             0.378495
hepatitis_b                        0.316340
bmi                                0.234627
schooling                          0.114926
adult_mortality                    0.059186
population                        -0.052123
diphtheria                        -0.557059
polio                             -0.593562
infant_deaths                     -0.627456
under-five_deaths                 -0.629343
thinness__1-19_years              -0.721273
thinness_5-9_years                -0.723473
hiv/aids                                NaN
Name: life_expectancy, dtype: float64

In [214]:
#7.Qual a posiçao do Brasil em relação a expectativa de vida?
#Países analisados: 163
#Posição do Brasil: 79º
#Expectativa de vida média: 73,38 anos, Brasil está 9 anos atrás do líder,
#indicando que indicadores de saúde, nutrição e socioeconômicos ainda podem ser aprimorados.
ranking_df = ranking.reset_index()
ranking_df['rank'] = ranking_df['life_expectancy'].rank(ascending=False, method='min')

ranking_df[ranking_df['country'] == 'Brazil']

   country  life_expectancy  rank
79  Brazil         73.38125  80.0

In [211]:
#8.Quais os 10 países com maior variação na expectativa de vida ao longo do
#período analisado?
df_variacao = df.groupby('country', as_index=False)['life_expectancy'] \
               .agg(lambda x: x.max() - x.min())

df_variacao.sort_values(by='life_expectancy', ascending=False).head(10)

                         country  life_expectancy
72                         Haiti             28.7
192                     Zimbabwe             22.7
55                       Eritrea             21.7
179                       Uganda             20.4
141                       Rwanda             19.7
21                      Botswana             19.7
191                       Zambia             19.2
122                        Niger             19.0
183  United Republic of Tanzania             17.8
95                       Liberia             17.0

In [149]:
#9.Qual a relação entre escolaridade e a expectativa de vida?
#“Observa-se uma forte correlação positiva (0.75) entre escolaridade e expectativa de vida,
#indicando que países com maior nível educacional tendem a apresentar melhores indicadores de longevidade.”
#Quanto maior a escolaridade, maior tende a ser a expectativa de vida.
df[['life_expectancy', 'schooling']].corr()

                 life_expectancy  schooling
life_expectancy         1.000000   0.751975
schooling               0.751975   1.000000

In [151]:
#10.Qual a relação entre o PIB de uma país e a expectativa de vida?
#Países com maior PIB tendem a ter maior expectativa de vida, mas não é uma relação
#tão forte quanto educação.
#País pode ser rico, mas ter desigualdade alta.
df[['life_expectancy', 'gdp']].corr()

                 life_expectancy       gdp
life_expectancy         1.000000  0.461455
gdp                     0.461455  1.000000

In [168]:
#11.Quais países com maior aumento na expectativa de vida ao longo dos anos?
#A análise de mínimo, máximo e média da expectativa de vida por país permite
#identificar padrões de evolução, estabilidade e desigualdade global ao longo
#do tempo.
print(df.groupby("country")["life_expectancy"].agg(["min", "max", "mean"]))

                                     min   max      mean
country
Afghanistan                         54.8  65.0  58.19375
Albania                             72.6  77.8  75.15625
Algeria                             71.3  75.6  73.61875
Angola                              45.3  56.0  49.01875
Antigua and Barbuda                 73.6  76.4  75.05625
...                                  ...   ...       ...
Venezuela (Bolivarian Republic of)  72.4  74.1  73.38750
Viet Nam                            73.4  76.0  74.77500
Yemen                               61.1  68.0  63.86250
Zambia                              43.8  63.0  53.90625
Zimbabwe                            44.3  67.0  50.48750

[193 rows x 3 columns]